### ISSUE TITLE
Looking at horse with animal info option on and shaders results in "foggy" screen

### ISSUE THREAD

**Issue by Lorsieab2** [cyilin/zyinhud-update#2]
I also noticed that when i turn on animal info and put my crosshair on a horse, my screen turns all "foggy".  It does show the horse's stats at first, but there's this whiteness at the bottom of the screen that starts spreading accross it. It's hard to describe. It only happens when I put horse stats on, and when I'm actually looking at a horse or am riding on one. I can't see anything when it happens and it's really annoying. I have optifine and kuda shaders on, both are the latest version. My minecraft is 1.10.2. Please fix this!

**Comment by Lorsieab2** [comment]
I think i put these in the wrong section. I meant to put this issue and the other one in the main release  for 1.10.2, the latest one xD

**Comment by cyilin** [comment]
Fixed, try latest version
